function createProduct() {
    if (localStorage.getItem('bookproduct') == null){
    let bookproduct = [
            {Masanpham: 'T01', name: 'The Catcher in the Rye', description: ' là một tiểu thuyết của tác giả người Mỹ JD Salinger được xuất bản một phần dưới dạng nhiều kỳ vào năm 1945–46 trước khi được chuyển thể thành tiểu thuyết vào năm 1951.', price: '$10.00', image1: './asset/img/Book1.png', quantity: 1, theloai: 'Tiểu thuyết', isNew: false},
            {Masanpham: 'T02', name: 'The Adventures Of Huckleberry Finn ', description: 'Là tiểu thuyết được xuất bản năm 1884 của nhà văn Mỹ Mark Twain. Tác phẩm được viết ở ngôi thứ nhất , là một trong những tiểu thuyết Mỹ đầu tiên dùng phương ngữ để viết', price: '$20.00', image1: './asset/img/Book2.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'T03', name: 'One Flew Over the Cuckoo\'s Nest', description: 'là một tiểu thuyết của Ken Kesey được xuất bản vào năm 1962. Lấy bối cảnh tại một bệnh viện tâm thần ở Oregon , câu chuyện đóng vai trò là một nghiên cứu về các quá trình thể chế và tâm trí con người, bao gồm cả lời phê bình về ngành tâm thần học và sự tôn vinh các nguyên tắc cá nhân.', price: '$30.00', image1: './asset/img/Book3.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'C01', name: 'Les Miserables By Victor Hugo', description: 'Les Miserables hay \'The Wretched\' là tiểu thuyết sử thi của Victor Hugo về sự cứu chuộc, hy sinh, tình yêu và đau khổ. Nó kể về câu chuyện của một cựu tù nhân Jean Valjean, người đã trải qua 19 năm tàn khốc trong xiềng xích sau khi ăn cắp một ổ bánh mì', price: '$40.00', image1: './asset/img/Book4.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'C02', name: 'Great Expectations', description: 'à tiểu thuyết thứ mười ba của tác giả người Anh Charles Dickens và là tiểu thuyết hoàn thành áp chót của ông. Tiểu thuyết là một bildungsroman và mô tả quá trình giáo dục của một đứa trẻ mồ côi có biệt danh là Pip .', price: '$50.00', image1: './asset/img/Book5.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'C03', name: 'Lord of the Flies', description: 'à một cuốn tiểu thuyết đầu tay năm 1954 của tác giả người Anh đoạt giải Nobel William Golding. Cuốn sách nói về một nhóm các cậu bé người Anh bị mắc kẹt trên một hòn đảo hoang và nỗ lực thống trị đầy tai hại của chúng. Bao gồm sự căng thẳng giữa tư duy tập thể và tính cá nhân, phản ứng giữa lý trí và cảm xúc, và giữa đạo đức và sự vô luân.', price: '$60.00', image1: './asset/img/Book6.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'TL01', name: 'The Alchemist', description: 'là một tác phẩm văn học nổi tiếng của nhà văn người Brazil Paulo Coelho, được viết bằng tiếng Bồ Đào Nha và đã được dịch ra hơn 80 ngôn ngữ trên toàn thế giới. ', price: '$70.00', image1: './asset/img/Book7.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'TL02', name: 'War and Peace', description: ' miêu tả cuộc chiến tranh yêu nước 1812 như biến cố trung tâm có ý nghĩa quyết định không chỉ vận mệnh nước Nga mà toàn châu Âu, miêu tả số phận của cả dân tộc, nhiều tầng lớp xã hội rộng rãi trong một thời điểm nghiêm trọng.', price: '$80.00', image1: './asset/img/Book8.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'TL03', name: 'All Quiet on the Western Front', description: 'là tiểu thuyết đề tài phản chiến của Erich Maria Remarque, một cựu binh Đức từng tham gia Chiến tranh thế giới thứ nhất. ', price: '$90.00', image1: './asset/img/Book9.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'T04', name: 'the Origin of Species', description: 'là một trong các ấn phẩm khoa học tiêu biểu và là tác phẩm nòng cốt của ngành sinh học tiến hóa.', price: '$100.00', image1: './asset/img/Book10.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'C04', name: 'The Picture Of Doruan Gray', description: 'là tiểu thuyết duy nhất của nhà văn người Ireland Oscar Wilde và được in thành sách kể từ năm 1891.', price: '$110.00', image1: './asset/img/Book11.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'T05', name: 'To Kill a Mockingbird', description: 'là cuốn tiểu thuyết của Harper Lee; đây là cuốn tiểu thuyết rất được yêu chuộng, thuộc loại bán chạy nhất thế giới với hơn 10 triệu bản. ', price: '$120.00', image1: './asset/img/Book12.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'TL04', name: 'Crime And Punishment', description: 'là một tiểu thuyết của nhà văn Nga Fyodor Mikhailovich Dostoyevsky. Tiểu thuyết này cùng với Anh em nhà Karamazov là hai tác phẩm nổi tiếng nhất của Dostoevsky.', price: '$130.00', image1: './asset/img/Book13.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'TL05', name: 'Moby-Dick', description: 'là một tiểu thuyết phiêu lưu mạo hiểm của tác giả người Mỹ Herman Melville và được xuất bản lần đầu tiên vào năm 1851, được coi là một tiểu thuyết Mỹ vĩ đại và một kho tàng văn học thế giới. ', price: '$140.00', image1: './asset/img/Book14.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'C05', name: 'Brave New World', description: ' là tiểu thuyết nổi tiếng của Aldous Huxley, được ra mắt năm 1932. Trong đó, tác giả đã kỳ công xây dựng nên một thế giới giả tưởng hoàn mỹ, nơi con người được tạo ra và phân cấp ngay từ ngày chào đời.', price: '$150.00', image1: './asset/img/Book15.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'T06', name: 'Hamlet', description: ' là vở bi - hài kịch của nhà văn, nhà soạn kịch người Anh William Shakespeare, có lẽ được sáng tác vào năm 1601. Cốt truyện của tác phẩm có nguồn gốc từ thể loại Saga (truyện dân gian) thời đại Trung cổ.', price: '$160.00', image1: './asset/img/Book16.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'C06', name: 'The Great Gatsby', description: 'là một tiểu thuyết của nhà văn F. Scott Fitzgerald người Mỹ, được xuất bản lần đầu vào ngày 10 tháng 4 năm 1925.', price: '$170.00', image1: './asset/img/Book17.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'TL06', name: ' Pride and Prejudice', description: ' là một tiểu thuyết của nhà văn Anh Jane Austen, xuất bản năm 1813. Câu chuyện nói về tình yêu và hôn nhân của tầng lớp quý tộc nhỏ tại Anh vào đầu thế kỷ 19. ', price: '$180.00', image1: './asset/img/Book18.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'T07', name: 'Little Women', description: 'là một tiểu thuyết của tác giả người Mỹ Louisa May Alcott ban đầu được xuất bản trong hai tập trong 1868 và 1869.', price: '$190.00', image1: './asset/img/Book19.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'C07', name: 'the diary of anne frank', description: 'là một cuốn sách bao gồm các trích đoạn từ một cuốn nhật ký do cô bé Anne Frank viết trong khi đang lẩn trốn cùng gia đình trong thời kỳ Đức Quốc xã chiếm đóng Hà Lan.', price: '$200.00', image1: './asset/img/Book20.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'T08', name: 'Product 21', description: 'Description for product 21.', price: '$210.00', image1: './asset/img/book21.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'TL07', name: 'Product 22', description: 'Description for product 22.', price: '$220.00', image1: './asset/img/book22.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'T09', name: 'Product 23', description: 'Description for product 23.', price: '$230.00', image1: './asset/img/book23.png', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'C08', name: 'Product 24', description: 'Description for product 24.', price: '$240.00', image1: './asset/img/book24.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'TL08', name: 'Product 25', description: 'Description for product 25.', price: '$250.00', image1: './asset/img/book25.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'C09', name: 'Product 26', description: 'Description for product 26.', price: '$260.00', image1: './asset/img/book25.png', quantity: 1, theloai: 'Chữa Lành', isNew: false},
            {Masanpham: 'TL09', name: 'Product 27', description: 'Description for product 27.', price: '$270.00', image1: './asset/img/book26.png', quantity: 1, theloai: 'Tâm Lý', isNew: false},
            {Masanpham: 'T10', name: 'Product 28', description: 'Description for product 28.', price: '$280.00', image1: './asset/img/sach1.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'T10', name: 'Product 29', description: 'Description for product 29.', price: '$290.00', image1: './asset/img/sach2.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'T10', name: 'Product 30', description: 'Description for product 30.', price: '$250.00', image1: './asset/img/sach3.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'T10', name: 'Product 31', description: 'Description for product 31.', price: '$220.00', image1: './asset/img/sach4.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: false},
            {Masanpham: 'T10', name: 'Product 32', description: 'Description for product 32.', price: '$230.00', image1: './asset/img/sach5.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: true},
            {Masanpham: 'T10', name: 'Product 33', description: 'Description for product 33.', price: '$180.00', image1: './asset/img/sach6.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: true},
            {Masanpham: 'T10', name: 'Product 34', description: 'Description for product 34.', price: '$400.00', image1: './asset/img/sach7.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: true},
            {Masanpham: 'T10', name: 'Product 35', description: 'Description for product 35.', price: '$80.00', image1: './asset/img/sach8.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: true},
            {Masanpham: 'T10', name: 'Product 36', description: 'Description for product 36.', price: '$40.00', image1: './asset/img/sach9.jpg', quantity: 1, theloai: 'Ngôn Tình', isNew: true}
];
    localStorage.setItem('bookproduct', JSON.stringify(bookproduct));
}
else {
    // Nếu đã có sản phẩm trong localStorage, lấy sản phẩm từ đó
    products = JSON.parse(localStorage.getItem('bookproduct'));
}
}

createProduct();